-- +goose Up
ALTER TABLE orders ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE orders ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE orders DROP COLUMN created_at;
ALTER TABLE orders DROP COLUMN updated_at;
