apiVersion: 1

contactPoints:
  - name: default-email
    receivers:
      - type: email
        settings:
          addresses: admin@example.com
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: default-email
    group_by: ['alertname', 'grafana_folder', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
